server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/JWT?
        useSSL=false&
        createDatabaseIfNotExist=true&
        useUnicode=true&
        characterEncoding=UTF-8&
        characterSetResults=UTF-8&
        allowPublicKeyRetrieval=true&
        serverTimezone=UTC&
        useLegacyDatetimeCode=false&
        useJDBCCompliantTimezoneShift=true
    username: root
    password: Welcome@123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  h2:
    console:
      enabled: true
  logging:
    level:
      org:
        springframework:
          security: DEBUG
  main:
    allow-circular-references: true


logout:
  url: http://localhost:8080/logout

SECRET_KEY: Ahmad Sukkar